// Extensive Bar Setup Library - Organized by Event/Function
// Premium bar setups for every Indian wedding and event occasion

export const BAR_SETUP_CATEGORIES = {
  events: [
    { id: 'all', label: 'All Events', icon: 'Sparkles' },
    { id: 'mehendi', label: 'Mehendi', icon: 'Flower2' },
    { id: 'haldi', label: 'Haldi', icon: 'Sun' },
    { id: 'sangeet', label: 'Sangeet', icon: 'Music' },
    { id: 'cocktail', label: 'Cocktail Night', icon: 'Wine' },
    { id: 'reception', label: 'Reception', icon: 'Crown' },
    { id: 'engagement', label: 'Engagement/Roka', icon: 'Heart' },
    { id: 'afterparty', label: 'After-Party', icon: 'PartyPopper' },
    { id: 'poolparty', label: 'Pool Party', icon: 'Waves' },
    { id: 'brunch', label: 'Brunch', icon: 'Coffee' },
    { id: 'corporate', label: 'Corporate', icon: 'Building2' },
  ],
  styles: [
    { id: 'all', label: 'All Styles' },
    { id: 'minimal-luxe', label: 'Minimal Luxe' },
    { id: 'royal', label: 'Royal Heritage' },
    { id: 'tropical', label: 'Tropical Paradise' },
    { id: 'bollywood', label: 'Bollywood Glam' },
    { id: 'modern', label: 'Modern Monochrome' },
    { id: 'rustic', label: 'Rustic Charm' },
    { id: 'garden', label: 'Garden Romance' },
    { id: 'industrial', label: 'Industrial Chic' },
    { id: 'bohemian', label: 'Bohemian Dream' },
  ],
  formats: [
    { id: 'all', label: 'All Formats' },
    { id: 'portable', label: 'Portable Bar' },
    { id: 'fixed', label: 'Fixed Installation' },
    { id: 'mobile-cart', label: 'Mobile Cart' },
    { id: 'pop-up', label: 'Pop-up Station' },
    { id: 'island', label: 'Island Bar' },
  ],
};

export const BAR_SETUPS_LIBRARY = [
  // ═══════════════════════════════════════════════════════════════════
  // MEHENDI SETUPS
  // ═══════════════════════════════════════════════════════════════════
  {
    id: 'mehendi-garden-bliss',
    slug: 'mehendi-garden-bliss',
    title: 'Garden Bliss Bar',
    subtitle: 'Floral elegance meets refreshing mocktails',
    description: 'A stunning garden-themed bar setup with cascading florals, pastel drapes, and botanical accents. Perfect for daytime mehendi ceremonies with refreshing fruit-infused mocktails and aromatic mist presentations.',
    image_url: 'https://customer-assets.emergentagent.com/job_e0f71186-1d36-4c69-8757-9da78c56fc4e/artifacts/v91pz5yr_freepik__a-candid-highresolution-dslr-photograph-of-a-stunn__34257.jpeg',
    gallery: [
      'https://customer-assets.emergentagent.com/job_e0f71186-1d36-4c69-8757-9da78c56fc4e/artifacts/v91pz5yr_freepik__a-candid-highresolution-dslr-photograph-of-a-stunn__34257.jpeg',
      'https://images.unsplash.com/photo-1551024709-8f23befc6f87?w=800&q=80',
      'https://images.unsplash.com/photo-1582106245687-cbb466a9f07f?w=800&q=80',
    ],
    events: ['mehendi', 'haldi', 'brunch'],
    style: 'garden',
    format: 'fixed',
    best_for: '100-200 guests',
    guest_range: { min: 100, max: 200 },
    molecular_techniques: ['Aromatic Mists', 'Flower Foam', 'Fruit Caviar'],
    molecular_tag: 'Aromatic Mists',
    features: [
      'Fresh floral arrangements',
      'Hanging botanical installations',
      'Custom fruit-infused drinks',
      'Instagram-worthy backdrop',
      'Ambient fairy lighting',
    ],
    signature_drinks: ['Rose Petal Spritzer', 'Mango Lassi Twist', 'Jasmine Iced Tea', 'Haldi Honey Cooler'],
    pricing_tier: 'premium',
    setup_time: '4-5 hours',
    staff_included: 4,
    featured: true,
  },
  {
    id: 'mehendi-moroccan-nights',
    slug: 'mehendi-moroccan-nights',
    title: 'Moroccan Nights',
    subtitle: 'Exotic vibes with intricate patterns',
    description: 'Transport your guests to Marrakech with this exotic setup featuring brass lanterns, colorful tiles, vibrant textiles, and aromatic mint-based concoctions with smoke bubble presentations.',
    image_url: 'https://customer-assets.emergentagent.com/job_e0f71186-1d36-4c69-8757-9da78c56fc4e/artifacts/fgci2d3q_Morracan%20Nights.png',
    gallery: [
      'https://customer-assets.emergentagent.com/job_e0f71186-1d36-4c69-8757-9da78c56fc4e/artifacts/fgci2d3q_Morracan%20Nights.png',
    ],
    events: ['mehendi', 'sangeet'],
    style: 'bohemian',
    format: 'fixed',
    best_for: '150-300 guests',
    guest_range: { min: 150, max: 300 },
    molecular_techniques: ['Smoke Bubbles', 'Aromatic Mists'],
    molecular_tag: 'Smoke Bubbles',
    features: [
      'Authentic Moroccan décor',
      'Brass lantern lighting',
      'Colorful tile accents',
      'Low seating lounge area',
      'Live mint tea service',
    ],
    signature_drinks: ['Moroccan Mint Mojito', 'Saffron Sunset', 'Orange Blossom Fizz', 'Spiced Date Shake'],
    pricing_tier: 'luxury',
    setup_time: '5-6 hours',
    staff_included: 5,
    featured: false,
  },
  {
    id: 'mehendi-pastel-paradise',
    slug: 'mehendi-pastel-paradise',
    title: 'Pastel Paradise',
    subtitle: 'Soft hues for dreamy celebrations',
    description: 'A delicate setup with soft pinks, lavenders, and mint greens. Features macramé accents, dried flower arrangements, and light, refreshing beverages perfect for afternoon mehendi.',
    image_url: 'https://customer-assets.emergentagent.com/job_e0f71186-1d36-4c69-8757-9da78c56fc4e/artifacts/giaxp0in_Pastel%20Paradise.png',
    gallery: [],
    events: ['mehendi', 'engagement'],
    style: 'minimal-luxe',
    format: 'portable',
    best_for: '50-150 guests',
    guest_range: { min: 50, max: 150 },
    molecular_techniques: ['Rose Foam', 'Edible Flowers'],
    molecular_tag: 'Rose Foam',
    features: [
      'Pastel color palette',
      'Macramé bar backdrop',
      'Dried flower installations',
      'Personalized drink tags',
      'Soft ambient music setup',
    ],
    signature_drinks: ['Lavender Lemonade', 'Peach Bellini Mocktail', 'Butterfly Pea Spritz', 'Cotton Candy Cloud'],
    pricing_tier: 'standard',
    setup_time: '3-4 hours',
    staff_included: 3,
    featured: true,
  },

  // ═══════════════════════════════════════════════════════════════════
  // HALDI SETUPS
  // ═══════════════════════════════════════════════════════════════════
  {
    id: 'haldi-sunshine-station',
    slug: 'haldi-sunshine-station',
    title: 'Sunshine Station',
    subtitle: 'Vibrant yellows and refreshing coolers',
    description: 'Embrace the golden hues of haldi with this sunshine-themed bar. Marigold garlands, yellow drapes, and turmeric-infused wellness drinks create the perfect festive atmosphere.',
    image_url: 'https://customer-assets.emergentagent.com/job_e0f71186-1d36-4c69-8757-9da78c56fc4e/artifacts/qg6xo5h0_Sunshine%20Station.png',
    gallery: [],
    events: ['haldi'],
    style: 'royal',
    format: 'portable',
    best_for: '50-100 guests',
    guest_range: { min: 50, max: 100 },
    molecular_techniques: ['Turmeric Foam', 'Aromatic Mists'],
    molecular_tag: 'Turmeric Foam',
    features: [
      'Marigold garland décor',
      'Traditional brass vessels',
      'Waterproof bar setup',
      'Splash-zone friendly',
      'Wellness drink menu',
    ],
    signature_drinks: ['Golden Milk Cooler', 'Mango Turmeric Lassi', 'Ginger Lime Fizz', 'Saffron Almond Shake'],
    pricing_tier: 'standard',
    setup_time: '2-3 hours',
    staff_included: 2,
    featured: true,
  },
  {
    id: 'haldi-marigold-magic',
    slug: 'haldi-marigold-magic',
    title: 'Marigold Magic',
    subtitle: 'Traditional charm with modern flair',
    description: 'A grand setup featuring thousands of marigolds, traditional brass elements, and ceremonial styling. Perfect for families who want an authentic yet luxurious haldi experience.',
    image_url: 'https://customer-assets.emergentagent.com/job_e0f71186-1d36-4c69-8757-9da78c56fc4e/artifacts/fc3meh85_Marigold%20magic.png',
    gallery: [],
    events: ['haldi', 'mehendi'],
    style: 'royal',
    format: 'fixed',
    best_for: '100-200 guests',
    guest_range: { min: 100, max: 200 },
    molecular_techniques: ['Aromatic Mists', 'Flower Foam'],
    molecular_tag: 'Aromatic Mists',
    features: [
      '10,000+ marigold flowers',
      'Brass urli centerpieces',
      'Traditional textile drapes',
      'Ceremonial vessel displays',
      'Photo-op corners',
    ],
    signature_drinks: ['Haldi Honey Latte', 'Kesari Thandai', 'Nimbu Pani Royale', 'Aam Panna Spritz'],
    pricing_tier: 'premium',
    setup_time: '4-5 hours',
    staff_included: 4,
    featured: false,
  },

  // ═══════════════════════════════════════════════════════════════════
  // SANGEET SETUPS
  // ═══════════════════════════════════════════════════════════════════
  {
    id: 'sangeet-bollywood-nights',
    slug: 'sangeet-bollywood-nights',
    title: 'Bollywood Nights',
    subtitle: 'Glamour, lights, and showstopping drinks',
    description: 'Channel the energy of Bollywood with this high-energy setup featuring LED panels, sequin backdrops, spotlight effects, and dramatic smoke bubble presentations synced to music.',
    image_url: 'https://customer-assets.emergentagent.com/job_ff2df9ce-7c56-472c-a16a-bca56f6db073/artifacts/broru5td_Bollywood%20Nights.png',
    gallery: [],
    events: ['sangeet', 'cocktail', 'afterparty'],
    style: 'bollywood',
    format: 'island',
    best_for: '200-400 guests',
    guest_range: { min: 200, max: 400 },
    molecular_techniques: ['Smoke Bubbles', 'LED Ice Cubes', 'Dry Ice Towers'],
    molecular_tag: 'Smoke Bubbles',
    features: [
      'LED panel backdrop',
      'Sequin décor elements',
      'Spotlight integration',
      'Music-synced smoke effects',
      'VIP bottle service area',
    ],
    signature_drinks: ['Disco Bomb', 'Starlight Martini', 'Bollywood Blast', 'Champagne Tower'],
    pricing_tier: 'luxury',
    setup_time: '6-8 hours',
    staff_included: 6,
    featured: true,
  },
  {
    id: 'sangeet-retro-disco',
    slug: 'sangeet-retro-disco',
    title: 'Retro Disco Bar',
    subtitle: '70s vibes with modern mixology',
    description: 'A nostalgic throwback to disco era with mirror balls, neon lights, funky patterns, and classic cocktails reimagined with molecular twists.',
    image_url: 'https://customer-assets.emergentagent.com/job_ff2df9ce-7c56-472c-a16a-bca56f6db073/artifacts/pcmrd5in_Retro%20Disco.png',
    gallery: [],
    events: ['sangeet', 'afterparty'],
    style: 'bollywood',
    format: 'fixed',
    best_for: '150-300 guests',
    guest_range: { min: 150, max: 300 },
    molecular_techniques: ['Color-Changing Drinks', 'Smoke Bubbles'],
    molecular_tag: 'Color-Changing Drinks',
    features: [
      'Authentic disco ball',
      'Neon signage',
      'Retro furniture',
      'Vinyl record décor',
      'Groovy playlist curation',
    ],
    signature_drinks: ['Funky Town Fizz', 'Disco Lemonade', 'Groovy Grape', 'Saturday Night Spritz'],
    pricing_tier: 'premium',
    setup_time: '5-6 hours',
    staff_included: 5,
    featured: false,
  },
  {
    id: 'sangeet-neon-dreams',
    slug: 'sangeet-neon-dreams',
    title: 'Neon Dreams',
    subtitle: 'Electric atmosphere with glowing drinks',
    description: 'A futuristic setup with UV-reactive elements, neon tube lighting, and glowing cocktails that light up under blacklight. Perfect for high-energy sangeet nights.',
    image_url: 'https://customer-assets.emergentagent.com/job_ff2df9ce-7c56-472c-a16a-bca56f6db073/artifacts/cz248ivj_Neon%20Dreams.png',
    gallery: [],
    events: ['sangeet', 'cocktail', 'afterparty'],
    style: 'modern',
    format: 'island',
    best_for: '200-500 guests',
    guest_range: { min: 200, max: 500 },
    molecular_techniques: ['UV Glowing Drinks', 'Smoke Bubbles', 'LED Ice'],
    molecular_tag: 'UV Glowing Drinks',
    features: [
      'UV blacklight zones',
      'Neon tube installations',
      'Glow-in-dark elements',
      'LED furniture',
      'Interactive light displays',
    ],
    signature_drinks: ['Electric Blue', 'Neon Sunrise', 'Glow Mojito', 'Radioactive Punch'],
    pricing_tier: 'luxury',
    setup_time: '6-7 hours',
    staff_included: 6,
    featured: true,
  },

  // ═══════════════════════════════════════════════════════════════════
  // COCKTAIL NIGHT SETUPS
  // ═══════════════════════════════════════════════════════════════════
  {
    id: 'cocktail-noir-elegance',
    slug: 'cocktail-noir-elegance',
    title: 'Noir Elegance',
    subtitle: 'Sophisticated black-tie glamour',
    description: 'The epitome of luxury with black marble finishes, gold accents, crystal glassware, and champagne foam presentations. For those who want their cocktail night to feel like a five-star experience.',
    image_url: 'https://customer-assets.emergentagent.com/job_ff2df9ce-7c56-472c-a16a-bca56f6db073/artifacts/cm3flarx_Noir.png',
    gallery: [],
    events: ['cocktail', 'reception'],
    style: 'minimal-luxe',
    format: 'island',
    best_for: '200-400 guests',
    guest_range: { min: 200, max: 400 },
    molecular_techniques: ['Champagne Foam', 'Gold Leaf Garnish', 'Smoke Cloche'],
    molecular_tag: 'Champagne Foam',
    features: [
      'Black marble bar top',
      'Gold accent details',
      'Crystal glassware',
      'Champagne tower display',
      'Live jazz corner',
    ],
    signature_drinks: ['Black Velvet', 'Gold Rush', 'Midnight Martini', 'Champagne Royale'],
    pricing_tier: 'luxury',
    setup_time: '6-8 hours',
    staff_included: 8,
    featured: true,
  },
  {
    id: 'cocktail-whiskey-lounge',
    slug: 'cocktail-whiskey-lounge',
    title: 'Whiskey Lounge',
    subtitle: 'Gentleman\'s club sophistication',
    description: 'A refined setup with leather accents, wooden bar, cigar lounge styling, and premium whiskey selection with smoke cloche presentations.',
    image_url: 'https://images.unsplash.com/photo-1572116469696-31de0f17cc34?w=800&q=80',
    gallery: [],
    events: ['cocktail', 'corporate', 'afterparty'],
    style: 'industrial',
    format: 'fixed',
    best_for: '100-200 guests',
    guest_range: { min: 100, max: 200 },
    molecular_techniques: ['Smoke Cloche', 'Whiskey Fog', 'Barrel Aging'],
    molecular_tag: 'Smoke Cloche',
    features: [
      'Leather bar stools',
      'Wooden barrel displays',
      'Cigar lounge styling',
      'Premium whiskey collection',
      'Private tasting area',
    ],
    signature_drinks: ['Smoked Old Fashioned', 'Maple Bourbon Sour', 'Highland Mist', 'Barrel-Aged Negroni'],
    pricing_tier: 'luxury',
    setup_time: '5-6 hours',
    staff_included: 5,
    featured: false,
  },
  {
    id: 'cocktail-speakeasy',
    slug: 'cocktail-speakeasy',
    title: 'Speakeasy Secret',
    subtitle: 'Prohibition-era mystique',
    description: 'A hidden gem setup with vintage décor, secret passwords, and classic cocktails with a modern molecular twist. Creates an exclusive, intimate atmosphere.',
    image_url: 'https://customer-assets.emergentagent.com/job_ff2df9ce-7c56-472c-a16a-bca56f6db073/artifacts/voucizw6_Speakeasy%20Secret.png',
    gallery: [],
    events: ['cocktail', 'engagement', 'afterparty'],
    style: 'industrial',
    format: 'pop-up',
    best_for: '50-150 guests',
    guest_range: { min: 50, max: 150 },
    molecular_techniques: ['Smoke Bubbles', 'Vintage Garnishes'],
    molecular_tag: 'Smoke Bubbles',
    features: [
      'Hidden entrance styling',
      'Vintage furniture',
      'Edison bulb lighting',
      'Secret menu cards',
      'Live jazz trio space',
    ],
    signature_drinks: ['Bee\'s Knees', 'French 75', 'Sidecar Deluxe', 'The Last Word'],
    pricing_tier: 'premium',
    setup_time: '4-5 hours',
    staff_included: 4,
    featured: true,
  },
  {
    id: 'cocktail-mirror-bar',
    slug: 'cocktail-mirror-bar',
    title: 'Mirror Mirror Bar',
    subtitle: 'Infinite reflections of luxury',
    description: 'A stunning mirror-finish bar that creates infinite reflections. LED underlighting, crystal chandeliers, and champagne foam presentations make this a showstopper.',
    image_url: 'https://customer-assets.emergentagent.com/job_ff2df9ce-7c56-472c-a16a-bca56f6db073/artifacts/aruhiixw_Mirror%20Mirror.png',
    gallery: [],
    events: ['cocktail', 'reception', 'engagement'],
    style: 'minimal-luxe',
    format: 'island',
    best_for: '200-500 guests',
    guest_range: { min: 200, max: 500 },
    molecular_techniques: ['Champagne Foam', 'Mirror Glaze', 'LED Ice'],
    molecular_tag: 'Champagne Foam',
    features: [
      'Full mirror bar surface',
      'LED underlighting',
      'Crystal chandelier',
      'Infinity effect walls',
      '360° service access',
    ],
    signature_drinks: ['Mirror Martini', 'Crystal Clear Negroni', 'Reflection Rosé', 'Infinity Fizz'],
    pricing_tier: 'luxury',
    setup_time: '7-8 hours',
    staff_included: 8,
    featured: true,
  },

  // ═══════════════════════════════════════════════════════════════════
  // RECEPTION SETUPS
  // ═══════════════════════════════════════════════════════════════════
  {
    id: 'reception-royal-heritage',
    slug: 'reception-royal-heritage',
    title: 'Royal Heritage',
    subtitle: 'Maharaja-style grandeur',
    description: 'Fit for royalty with carved wooden bar, velvet drapes, gold accents, and traditional brass elements. Includes champagne tower and personalized couple\'s signature cocktails.',
    image_url: 'https://customer-assets.emergentagent.com/job_ff2df9ce-7c56-472c-a16a-bca56f6db073/artifacts/0413fdxg_Royal%20Herritage.png',
    gallery: [],
    events: ['reception', 'engagement'],
    style: 'royal',
    format: 'fixed',
    best_for: '300-500 guests',
    guest_range: { min: 300, max: 500 },
    molecular_techniques: ['Champagne Foam', 'Dry Ice Towers', 'Gold Leaf'],
    molecular_tag: 'Champagne Foam',
    features: [
      'Hand-carved wooden bar',
      'Royal velvet drapes',
      'Traditional brass accents',
      'Champagne tower',
      'Live performance space',
    ],
    signature_drinks: ['Royal Elixir', 'Maharaja\'s Mule', 'Golden Palace', 'Regal Rose'],
    pricing_tier: 'luxury',
    setup_time: '8-10 hours',
    staff_included: 10,
    featured: true,
  },
  {
    id: 'reception-white-elegance',
    slug: 'reception-white-elegance',
    title: 'White Elegance',
    subtitle: 'Pure sophistication in white',
    description: 'An all-white setup with white florals, white linens, and clear acrylic elements. Creates a clean, sophisticated backdrop that photographs beautifully.',
    image_url: 'https://customer-assets.emergentagent.com/job_ff2df9ce-7c56-472c-a16a-bca56f6db073/artifacts/kuveeg2y_White%20Elegance.png',
    gallery: [],
    events: ['reception', 'engagement'],
    style: 'minimal-luxe',
    format: 'island',
    best_for: '200-400 guests',
    guest_range: { min: 200, max: 400 },
    molecular_techniques: ['White Foam', 'Pearl Dust', 'Dry Ice'],
    molecular_tag: 'White Foam',
    features: [
      'All-white color scheme',
      'White floral arrangements',
      'Clear acrylic elements',
      'Soft uplighting',
      'Minimalist elegance',
    ],
    signature_drinks: ['White Garden', 'Pearl Drop', 'Coconut Cloud', 'Vanilla Sky'],
    pricing_tier: 'premium',
    setup_time: '5-6 hours',
    staff_included: 6,
    featured: false,
  },
  {
    id: 'reception-garden-glam',
    slug: 'reception-garden-glam',
    title: 'Garden Glam',
    subtitle: 'Nature meets luxury',
    description: 'Perfect for outdoor receptions with cascading greenery, fairy lights, natural wood elements, and botanical cocktails with edible flower garnishes.',
    image_url: 'https://customer-assets.emergentagent.com/job_e0f71186-1d36-4c69-8757-9da78c56fc4e/artifacts/3vuvscmf_Garden%20Glam.png',
    gallery: [],
    events: ['reception', 'engagement', 'mehendi'],
    style: 'garden',
    format: 'fixed',
    best_for: '150-300 guests',
    guest_range: { min: 150, max: 300 },
    molecular_techniques: ['Edible Flowers', 'Aromatic Mists', 'Botanical Foams'],
    molecular_tag: 'Edible Flowers',
    features: [
      'Living green wall',
      'Fairy light canopy',
      'Reclaimed wood bar',
      'Botanical décor',
      'Garden seating area',
    ],
    signature_drinks: ['Garden Party', 'Elderflower Fizz', 'Botanical G&T', 'Rosemary Sunset'],
    pricing_tier: 'premium',
    setup_time: '5-6 hours',
    staff_included: 5,
    featured: true,
  },

  // ═══════════════════════════════════════════════════════════════════
  // ENGAGEMENT/ROKA SETUPS
  // ═══════════════════════════════════════════════════════════════════
  {
    id: 'engagement-intimate-luxe',
    slug: 'engagement-intimate-luxe',
    title: 'Intimate Luxe',
    subtitle: 'Small gathering, big impact',
    description: 'Designed for smaller engagement celebrations with personalized touches, couple\'s monogram, and intimate seating around the bar.',
    image_url: 'https://customer-assets.emergentagent.com/job_ff2df9ce-7c56-472c-a16a-bca56f6db073/artifacts/9aetrxkp_Intimate%20Lux.png',
    gallery: [],
    events: ['engagement', 'brunch'],
    style: 'minimal-luxe',
    format: 'portable',
    best_for: '30-80 guests',
    guest_range: { min: 30, max: 80 },
    molecular_techniques: ['Rose Foam', 'Personalized Ice'],
    molecular_tag: 'Rose Foam',
    features: [
      'Couple\'s monogram display',
      'Personalized drink menu',
      'Intimate bar seating',
      'Photo wall backdrop',
      'Custom signage',
    ],
    signature_drinks: ['Forever Yours', 'Proposal Toast', 'Ring Fizz', 'Couple\'s Creation'],
    pricing_tier: 'standard',
    setup_time: '2-3 hours',
    staff_included: 2,
    featured: true,
  },
  {
    id: 'engagement-rooftop-romance',
    slug: 'engagement-rooftop-romance',
    title: 'Rooftop Romance',
    subtitle: 'City lights and cocktails',
    description: 'Perfect for rooftop engagements with skyline views, twinkling lights, and elegant urban styling with champagne service.',
    image_url: 'https://customer-assets.emergentagent.com/job_ff2df9ce-7c56-472c-a16a-bca56f6db073/artifacts/3o86193u_Rooftop%20Romance.png',
    gallery: [],
    events: ['engagement', 'cocktail'],
    style: 'modern',
    format: 'portable',
    best_for: '50-150 guests',
    guest_range: { min: 50, max: 150 },
    molecular_techniques: ['Champagne Foam', 'Smoke Bubbles'],
    molecular_tag: 'Champagne Foam',
    features: [
      'Wind-resistant setup',
      'Twinkling light canopy',
      'Urban chic styling',
      'Champagne station',
      'City view integration',
    ],
    signature_drinks: ['Skyline Spritz', 'Rooftop Romance', 'City Lights', 'Stargazer'],
    pricing_tier: 'premium',
    setup_time: '3-4 hours',
    staff_included: 3,
    featured: false,
  },

  // ═══════════════════════════════════════════════════════════════════
  // AFTER-PARTY SETUPS
  // ═══════════════════════════════════════════════════════════════════
  {
    id: 'afterparty-club-vibes',
    slug: 'afterparty-club-vibes',
    title: 'Club Vibes',
    subtitle: 'Dance floor energy',
    description: 'High-energy club setup with DJ booth integration, LED bar panels, shot stations, and quick-serve cocktails for the dance crowd.',
    image_url: 'https://customer-assets.emergentagent.com/job_ff2df9ce-7c56-472c-a16a-bca56f6db073/artifacts/rwflqxe5_Club%20Vibes.png',
    gallery: [],
    events: ['afterparty', 'sangeet'],
    style: 'modern',
    format: 'island',
    best_for: '150-400 guests',
    guest_range: { min: 150, max: 400 },
    molecular_techniques: ['Smoke Shots', 'LED Ice', 'Dry Ice Towers'],
    molecular_tag: 'Smoke Shots',
    features: [
      'DJ booth integration',
      'LED bar panels',
      'Shot stations',
      'Quick-serve setup',
      'Dance floor adjacent',
    ],
    signature_drinks: ['Party Starter', 'Drop Shot', 'Electric Slide', 'Midnight Heat'],
    pricing_tier: 'premium',
    setup_time: '5-6 hours',
    staff_included: 6,
    featured: true,
  },
  {
    id: 'afterparty-late-night-lounge',
    slug: 'afterparty-late-night-lounge',
    title: 'Late Night Lounge',
    subtitle: 'Chill vibes till dawn',
    description: 'Relaxed lounge setup for winding down after the main event. Comfortable seating, mood lighting, and easy-sipping cocktails.',
    image_url: 'https://customer-assets.emergentagent.com/job_ff2df9ce-7c56-472c-a16a-bca56f6db073/artifacts/gqm3e8fj_late%20night.png',
    gallery: [],
    events: ['afterparty'],
    style: 'industrial',
    format: 'fixed',
    best_for: '50-150 guests',
    guest_range: { min: 50, max: 150 },
    molecular_techniques: ['Aromatic Mists', 'Smoke Cloche'],
    molecular_tag: 'Aromatic Mists',
    features: [
      'Lounge seating',
      'Mood lighting',
      'Hookah integration',
      'Late-night snack pairing',
      'Chill playlist curation',
    ],
    signature_drinks: ['Night Cap', 'Moon Glow', 'Velvet Hour', 'Last Dance'],
    pricing_tier: 'standard',
    setup_time: '3-4 hours',
    staff_included: 3,
    featured: false,
  },

  // ═══════════════════════════════════════════════════════════════════
  // POOL PARTY SETUPS
  // ═══════════════════════════════════════════════════════════════════
  {
    id: 'pool-tropical-splash',
    slug: 'pool-tropical-splash',
    title: 'Tropical Splash',
    subtitle: 'Island paradise poolside',
    description: 'Transport guests to a tropical island with tiki bar styling, palm fronds, floating drink service, and refreshing frozen cocktails.',
    image_url: 'https://customer-assets.emergentagent.com/job_ff2df9ce-7c56-472c-a16a-bca56f6db073/artifacts/bwa7g8ze_tropical.png',
    gallery: [],
    events: ['poolparty', 'mehendi'],
    style: 'tropical',
    format: 'fixed',
    best_for: '100-200 guests',
    guest_range: { min: 100, max: 200 },
    molecular_techniques: ['Frozen Drinks', 'Fruit Caviar', 'Coconut Smoke'],
    molecular_tag: 'Frozen Drinks',
    features: [
      'Tiki bar styling',
      'Palm frond décor',
      'Floating drink trays',
      'Waterproof setup',
      'Poolside service',
    ],
    signature_drinks: ['Piña Colada', 'Blue Lagoon', 'Mango Tango', 'Coconut Dream'],
    pricing_tier: 'premium',
    setup_time: '4-5 hours',
    staff_included: 5,
    featured: true,
  },
  {
    id: 'pool-ibiza-beach',
    slug: 'pool-ibiza-beach',
    title: 'Ibiza Beach Club',
    subtitle: 'European beach party vibes',
    description: 'Mediterranean-inspired setup with white and blue color scheme, beach beds, and premium cocktails in a beach club atmosphere.',
    image_url: 'https://customer-assets.emergentagent.com/job_ff2df9ce-7c56-472c-a16a-bca56f6db073/artifacts/iwhkd47p_ibiza.png',
    gallery: [],
    events: ['poolparty', 'brunch'],
    style: 'modern',
    format: 'island',
    best_for: '150-300 guests',
    guest_range: { min: 150, max: 300 },
    molecular_techniques: ['Mediterranean Foam', 'Citrus Mists'],
    molecular_tag: 'Mediterranean Foam',
    features: [
      'White cabana setups',
      'Beach bed seating',
      'Blue and white décor',
      'DJ booth space',
      'Bottle service',
    ],
    signature_drinks: ['Sangria Splash', 'Mediterranean Mule', 'Grecian Goddess', 'Ibiza Sunset'],
    pricing_tier: 'luxury',
    setup_time: '5-6 hours',
    staff_included: 6,
    featured: false,
  },

  // ═══════════════════════════════════════════════════════════════════
  // BRUNCH SETUPS
  // ═══════════════════════════════════════════════════════════════════
  {
    id: 'brunch-champagne-garden',
    slug: 'brunch-champagne-garden',
    title: 'Champagne Garden',
    subtitle: 'Bubbly morning elegance',
    description: 'Light, airy setup perfect for day events with mimosa bars, fresh juice stations, and champagne fountains amidst garden-style décor.',
    image_url: 'https://images.unsplash.com/photo-1566417713940-fe7c737a9ef2?w=800&q=80',
    gallery: [],
    events: ['brunch', 'mehendi', 'engagement'],
    style: 'garden',
    format: 'portable',
    best_for: '50-150 guests',
    guest_range: { min: 50, max: 150 },
    molecular_techniques: ['Champagne Foam', 'Fresh Juice Mists'],
    molecular_tag: 'Champagne Foam',
    features: [
      'Mimosa bar station',
      'Fresh juice display',
      'Champagne fountain',
      'Garden furniture',
      'Morning light optimized',
    ],
    signature_drinks: ['Classic Mimosa', 'Bellini Bar', 'Fresh Squeezed Sunrise', 'Elderflower Fizz'],
    pricing_tier: 'standard',
    setup_time: '2-3 hours',
    staff_included: 3,
    featured: true,
  },

  // ═══════════════════════════════════════════════════════════════════
  // CORPORATE SETUPS
  // ═══════════════════════════════════════════════════════════════════
  {
    id: 'corporate-executive-bar',
    slug: 'corporate-executive-bar',
    title: 'Executive Bar',
    subtitle: 'Professional sophistication',
    description: 'Clean, professional setup suitable for corporate events with branded elements, premium spirits selection, and sophisticated styling.',
    image_url: 'https://images.unsplash.com/photo-1560624052-449f5ddf0c31?w=800&q=80',
    gallery: [],
    events: ['corporate'],
    style: 'modern',
    format: 'fixed',
    best_for: '100-300 guests',
    guest_range: { min: 100, max: 300 },
    molecular_techniques: ['Smoke Cloche', 'Premium Ice'],
    molecular_tag: 'Smoke Cloche',
    features: [
      'Brand integration',
      'Logo placement',
      'Corporate colors',
      'Professional staff',
      'VIP service options',
    ],
    signature_drinks: ['Corporate Classic', 'Executive Martini', 'Boardroom Bourbon', 'Success Spritz'],
    pricing_tier: 'premium',
    setup_time: '4-5 hours',
    staff_included: 5,
    featured: false,
  },
  {
    id: 'corporate-product-launch',
    slug: 'corporate-product-launch',
    title: 'Product Launch Bar',
    subtitle: 'Create buzz with every sip',
    description: 'Custom-themed bar designed around your product launch with branded cocktails, interactive elements, and social media-worthy presentations.',
    image_url: 'https://images.unsplash.com/photo-1540575467063-178a50c2df87?w=800&q=80',
    gallery: [],
    events: ['corporate'],
    style: 'modern',
    format: 'island',
    best_for: '200-500 guests',
    guest_range: { min: 200, max: 500 },
    molecular_techniques: ['Custom Branded Drinks', 'Smoke Effects', 'LED Integration'],
    molecular_tag: 'Custom Branded Drinks',
    features: [
      'Full brand customization',
      'Product integration',
      'Social media wall',
      'Interactive stations',
      'Press-ready setup',
    ],
    signature_drinks: ['Product Signature', 'Launch Toast', 'Brand Builder', 'Innovation Elixir'],
    pricing_tier: 'luxury',
    setup_time: '6-8 hours',
    staff_included: 8,
    featured: true,
  },

  // ═══════════════════════════════════════════════════════════════════
  // ADDITIONAL PREMIUM SETUPS
  // ═══════════════════════════════════════════════════════════════════
  {
    id: 'rustic-barn',
    slug: 'rustic-barn',
    title: 'Rustic Barn Bar',
    subtitle: 'Countryside charm',
    description: 'Reclaimed wood bar with mason jar displays, wildflower arrangements, and farm-to-glass cocktails for rustic-themed celebrations.',
    image_url: 'https://images.unsplash.com/photo-1510812431401-41d2bd2722f3?w=800&q=80',
    gallery: [],
    events: ['reception', 'engagement', 'mehendi'],
    style: 'rustic',
    format: 'fixed',
    best_for: '100-250 guests',
    guest_range: { min: 100, max: 250 },
    molecular_techniques: ['Herb Smoke', 'Honey Foam'],
    molecular_tag: 'Herb Smoke',
    features: [
      'Reclaimed wood bar',
      'Mason jar displays',
      'Wildflower décor',
      'Barrel accents',
      'String light canopy',
    ],
    signature_drinks: ['Barn Dance', 'Countryside Mule', 'Honey Harvest', 'Apple Orchard'],
    pricing_tier: 'standard',
    setup_time: '4-5 hours',
    staff_included: 4,
    featured: true,
  },
  {
    id: 'minimalist-acrylic',
    slug: 'minimalist-acrylic',
    title: 'Minimalist Acrylic',
    subtitle: 'Clean lines, pure elegance',
    description: 'Ultra-modern clear acrylic bar with minimal styling, perfect for contemporary venues where the drinks become the art.',
    image_url: 'https://images.unsplash.com/photo-1582106245687-cbb466a9f07f?w=800&q=80',
    gallery: [],
    events: ['cocktail', 'corporate', 'reception'],
    style: 'minimal-luxe',
    format: 'island',
    best_for: '150-400 guests',
    guest_range: { min: 150, max: 400 },
    molecular_techniques: ['Crystal Clear Ice', 'Minimalist Garnish'],
    molecular_tag: 'Crystal Clear Ice',
    features: [
      'Clear acrylic construction',
      'LED color options',
      'Modern minimalism',
      'Clean-line design',
      'High-end finishes',
    ],
    signature_drinks: ['Crystal Clear', 'Minimal Martini', 'Pure & Simple', 'Clean Slate'],
    pricing_tier: 'premium',
    setup_time: '4-5 hours',
    staff_included: 5,
    featured: false,
  },
];

// Helper functions
export const getSetupsByEvent = (eventId) => {
  if (eventId === 'all') return BAR_SETUPS_LIBRARY;
  return BAR_SETUPS_LIBRARY.filter(setup => setup.events.includes(eventId));
};

export const getSetupsByStyle = (styleId) => {
  if (styleId === 'all') return BAR_SETUPS_LIBRARY;
  return BAR_SETUPS_LIBRARY.filter(setup => setup.style === styleId);
};

export const getFeaturedSetups = () => {
  return BAR_SETUPS_LIBRARY.filter(setup => setup.featured);
};

export const getSetupBySlug = (slug) => {
  return BAR_SETUPS_LIBRARY.find(setup => setup.slug === slug);
};

export const filterSetups = ({ event, style, format, guestCount }) => {
  return BAR_SETUPS_LIBRARY.filter(setup => {
    if (event && event !== 'all' && !setup.events.includes(event)) return false;
    if (style && style !== 'all' && setup.style !== style) return false;
    if (format && format !== 'all' && setup.format !== format) return false;
    if (guestCount && (guestCount < setup.guest_range.min || guestCount > setup.guest_range.max)) return false;
    return true;
  });
};
